import Link from "next/link";
import "./layout.css";

export default function Layout({ children }) {
  return (
    <html lang="es">
      <head>
        <title>FacturaSmart ORT</title>
      </head>
      <body>
        <div className="layout">
          <header>
            <nav className="navbar"></nav>
          </header>

          <main className="content">{children}</main>

          <footer className="footer">
            <p>© 2024 Grupo2-ORT - Todos los derechos reservados.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}

// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
